import './globals.css'
import { Inter } from 'next/font/google'
import classNames from 'classnames';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const bodyClasses = classNames(inter.className, 'min-h-screen');

  return (
    <html lang="en">
      <body className={bodyClasses}>{children}</body>
    </html>
  )
}
